#!/usr/bin/env python

import argparse
import signal
import sys
import numpy as np

import sm
import kalibr_common as kc
from kalibr_imu_camera_calibration import Simulator

# make numpy print prettier
np.set_printoptions(suppress=True)

def signal_exit(signal, frame):
    print
    sm.logWarn("Shutting down! (CTRL+C)")
    sys.exit(1)

#helper to constrain certain arguments to be specified only once
class Once(argparse.Action):
    def __call__(self, parser, namespace, values, option_string = None):
        if getattr(namespace, self.dest) is not None:
            msg = '{o} can only be specified once'.format(o = option_string)
            raise argparse.ArgumentError(None, msg)
        setattr(namespace, self.dest, values)

def parseArgs():
    class KalibrArgParser(argparse.ArgumentParser):
        def error(self, message):
            self.print_help()
            sm.logError('%s' % message)
            sys.exit(2)
        def format_help(self):
            formatter = self._get_formatter()
            formatter.add_text(self.description)
            formatter.add_usage(self.usage, self._actions,
                                self._mutually_exclusive_groups)
            for action_group in self._action_groups:
                formatter.start_section(action_group.title)
                formatter.add_text(action_group.description)
                formatter.add_arguments(action_group._group_actions)
                formatter.end_section()
            formatter.add_text(self.epilog)
            return formatter.format_help()

    usage = """
    Example usage to generate the visual inertial system states at specific epochs and
     observations of a calibration target with a rolling shutter camera model and
     inertial measurements based on a given B-spline in the 15 dimensional state space.
    
    %(prog)s --cam camchain.yaml --target aprilgrid.yaml --time-calibration
    
    camchain.yaml: like the camera-IMU system calibration output of the camera-imu
                   calibratin tool (kalibr_calibrate_cameras)
    
    example aprilgrid.yaml:       |  example imu.yaml: (ADIS16448)
        target_type: 'aprilgrid'  |      accelerometer_noise_density: 0.006  
        tagCols: 6                |      accelerometer_random_walk: 0.0002
        tagRows: 6                |      gyroscope_noise_density: 0.0004
        tagSize: 0.088            |      gyroscope_random_walk: 4.0e-06
        tagSpacing: 0.3           |      update_rate: 200.0"""

    #setup the argument list
    parser = KalibrArgParser(description='Simulate rolling shutter camera measurements and inertial readings.', usage=usage)

    #simulation options
    groupSim = parser.add_argument_group('Simulation options')
    groupSim.add_argument('pose_file', help='The file of the knot coefficients of the pose B spline')
    groupSim.add_argument('--gyro-bias-file', dest='gyro_bias_file', \
            help=('The file of the knot coefficients of the gyro bias B spline.'
                  ' If not specified, it will be deduced from the pose_file!'))
    groupSim.add_argument('--acc-bias-file', dest='acc_bias_file', \
            help=('The file of the knot coefficients of the accelerometer bias B spline.'
                  ' If not specified, it will be deduced from the pose_file!'))
    groupSim.add_argument('--output_dir', help='Where to put output files?')
    groupSim.add_argument('--bias-from-splines', action='store_true', dest='biasFromSplines',
                          help=('Simulate IMU biases from provided bias splines? '
                               'Or else generate noise per IMU parameters.'))
    groupSim.add_argument('--dont-show-report', action='store_true', dest='dontShowReport',
                          help='Do not show the report on screen after simulation.')

    #configuration files
    groupCam = parser.add_argument_group('Camera system configuration')
    groupCam.add_argument('--cam', dest='chain_yaml', help='Camera-IMU system configuration as yaml file', required=True, action=Once)
    groupCam.add_argument('--reprojection-sigma', type=float, default=1.0, dest='reprojection_sigma', \
            help='Standard deviation of the distribution of reprojected corner points [px]. (default: %(default)s)')

    groupImu = parser.add_argument_group('IMU configuration')
    groupImu.add_argument('--imu', dest='imu_yaml', help=('Yaml holding the IMU noise parameters.'
            ' Thanks to the ConfigReader, no hierarchy should be used in the yaml.'))
    groupImu.add_argument('--imu-model', dest='imu_model', help= \
            ('The IMU models to estimate. Currently supported are \'calibrated\','
             ' \'scale-misalignment\' and \'scale-misalignment-size-effect\'.'))

    groupTarget = parser.add_argument_group('Calibration target')
    groupTarget.add_argument('--target', dest='target_yaml', help='Calibration target configuration as yaml file',
                             required=True, action=Once)

    #print help if no argument is specified
    if len(sys.argv)==1:
        parser.print_help()
        sys.exit(2)

    #Parser the argument list
    try:
        parsed = parser.parse_args()
    except:
        sys.exit(2)
    return parsed

def main():
    # Parse the arguments
    parsed = parseArgs()
    if not parsed.gyro_bias_file:
        parsed.gyro_bias_file = parsed.pose_file.replace('pose', 'gyro_bias', 1)
    if not parsed.acc_bias_file:
        parsed.acc_bias_file = parsed.pose_file.replace('pose', 'acc_bias', 1)

    if  parsed.imu_yaml and not parsed.imu_model:
        #Maintain backwards compatibility with previous interface.
        parsed.imu_model = 'calibrated'

    print("Loading B splines...")
    simulator = Simulator.RsVisualInertialMeasViaBSplineSimulator(parsed)
    # simulator.checkNaiveVsNewtonRsProjection()

    simulator.simulate(parsed.output_dir)

if __name__ == "__main__":
    main()
