#!/usr/bin/env python3
"""
Estimate the IMU noise parameters in a camera-IMU calibration setup.

Algorithm
Initialize the noise parameters from experience.
Repeat two steps:
1. read the noise parameters, then perform camera-IMU calibration with these parameters, 
2. compute and save the noise distribution parameters from the residuals.
Stop when the noise parameters or the total cost do not change much.
"""

import kalibr_common as kc
from kalibr_imu_camera_calibration import *

import os
this_dir = os.path.dirname(os.path.abspath(__file__))
script_calibrate_imu_camera = os.path.join(this_dir, 'kalibr_calibrate_imu_camera')
print(script_calibrate_imu_camera)

import imp
kalibr_calibrate_imu_camera = imp.load_source('kalibr_calibrate_imu_camera', script_calibrate_imu_camera)

import shutil

def loadText(fn):
    lines = []
    with open(fn, 'r') as stream:
        for line in stream:
            lines.append(line) # Note this keeps the newline character.
    return lines


def dumpText(lines, fn):
    with open(fn, 'w') as stream:
        for line in lines:
            stream.write("{}".format(line))


def addParserArguments(parser):
    groupNoise = parser.add_argument_group('Noise identification')
    groupNoise.add_argument('--max_noise_opt_iters', type=int, default = 5,
                            help='max number of iterations for IMU noise optimization. (default: %(default)s)')


def main():
    parser = kalibr_calibrate_imu_camera.createParser()
    addParserArguments(parser)
    args = kalibr_calibrate_imu_camera.parseArgs(parser)

    # For safety, we will work on the copy of the imu yamls.
    imu_yamls_orig = args.imu_yamls
    imu_yamls = []
    for imufile in imu_yamls_orig:
        dst = os.path.basename(os.path.splitext(imufile)[0]) + "_temp.yaml"
        shutil.copyfile(imufile, dst)
        imu_yamls.append(dst)
    args.imu_yamls = imu_yamls

    chain_yaml_orig = args.chain_yaml
    chain_yaml = os.path.basename(os.path.splitext(chain_yaml_orig)[0]) + "_temp.yaml"
    shutil.copyfile(chain_yaml_orig, chain_yaml)
    args.chain_yaml = chain_yaml

    args.identifyNoises = True
    noiseParameterNames = ["accelerometer_noise_density", "accelerometer_random_walk", 
           "gyroscope_noise_density", "gyroscope_random_walk"]

    for outerLoopId in range(5):
        if outerLoopId == 0:
            args.saveVimap = True
        else:
            args.saveVimap = False
        residualStats = kalibr_calibrate_imu_camera.calibrate_imu_camera(args)
        print('Final cost function value {}'.format(residualStats['JFinal']))

        # update camera noise
        for camId in range(len(residualStats) - 2):
            camName = 'cam{}'.format(camId)
            if camName in residualStats:
                data = residualStats[camName]
                print('\nCamera {} noises:'.format(camId))
                print('\timage_noise_std_dev: {}'.format(data["image_noise_std_dev"]))

                lines = loadText(args.chain_yaml)
                occurrence = 0
                for lid, line in enumerate(lines):
                    if "image_noise_std_dev" in line:
                        if occurrence == camId:
                            lines[lid] = "  image_noise_std_dev: {}\n".format(np.average(data["image_noise_std_dev"]))
                            break
                        occurrence += 1
                dumpText(lines, chain_yaml)

        # update IMU noise
        for imuId in range(len(residualStats) - 2):
            imuName = 'imu{}'.format(imuId)
            if imuName in residualStats:
                data = residualStats[imuName]
                print('\nIMU {} noises:'.format(imuId))
                for noise in noiseParameterNames:
                    print('\t{}: {}'.format(noise, data[noise]))
                
                lines = loadText(imu_yamls[imuId])
                for lid, line in enumerate(lines):
                    for noise in ["accelerometer_noise_density", "gyroscope_noise_density"]:
                        if noise in line:
                            lines[lid] = "{}: {}\n".format(noise, np.average(data[noise]))
                            break
                    # TODO(jhuai): maybe we should not update random walk parameters.
                    # for noise in ["accelerometer_random_walk", "gyroscope_random_walk"]:
                    #     if noise in line:
                    #         lines[lid] = "{}: {}\n".format(noise, np.average(data[noise][2, 1:]))
                    #         break
                dumpText(lines, imu_yamls[imuId])
    print('The identified IMU noise parameters are at {}!'.format('\n\t'.join(imu_yamls)))


if __name__ == "__main__":
    main()
